FROM node:22-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    tini \
    git \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN corepack enable

RUN useradd \
    --create-home \
    --shell /bin/bash \
    sandbox

WORKDIR /workspace

COPY warm-template/package.json ./
COPY warm-template/bun-lock.yaml ./

RUN bun install \
  --frozen-lockfile

COPY warm-template/ .

RUN chown -R sandbox:sandbox /workspace

USER sandbox

ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=5173

EXPOSE 5173

ENTRYPOINT ["tini", "--"]


CMD ["bun" , "dev" ,"--host" , 0.0.0.0]
